# Generated by Django 5.0.4 on 2024-06-23 07:03

from django.db import migrations





class Migration(migrations.Migration):

    def set_age_group(apps, schema_editor):
        person_model = apps.get_model('main_app', 'Person')
        persons = person_model.objects.all()

        for p in persons:
            if p.age <= 12:
                p.age_group = 'Child'
            elif p.age <= 17:
                p.age_group = 'Teen'
            else:
                p.age_group = 'Adult'

        person_model.objects.bulk_update(persons, ['age_group'])


    def set_age_group_default(apps, schema_editor):
        person_model = apps.get_model('main_app', 'Person')
        persons = person_model.objects.all()

        age_group_default = person_model._meta.get_field('age_group').default

        for p in persons:
            p.age_group = age_group_default

        person_model.objects.bulk_update(persons, ['age_group'])

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=set_age_group_default)
    ]
