# Generated by Django 5.0.4 on 2024-06-23 07:29

from django.db import migrations


def generate_price(apps, schema_editor):
    price_multiplier = 120

    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    for s in smartphones:
        s.price = len(s.brand) * price_multiplier

    smartphone_model.objects.bulk_update(smartphones, ['price'])


def generate_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    for s in smartphones:
        if s.price < 750:
            s.category = 'Cheap'
        else:
            s.category = 'Expensive'

    smartphone_model.objects.bulk_update(smartphones, ['category'])


def set_default(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    default_price = smartphone_model._meta.get_field('price').default
    default_category = smartphone_model._meta.get_field('category').default

    for s in smartphones:
        s.price = default_price
        s.category = default_category

    smartphone_model.objects.bulk_update(smartphones, ['price', 'category'])


def generate_price_category(apps, schema_editor):
    generate_price(apps, schema_editor)
    generate_category(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(generate_price_category, reverse_code=set_default)
    ]
