# Generated by Django 5.0.4 on 2024-06-23 07:58

from django.db import migrations
from django.utils import timezone


def update_delivery_warranty(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')
    orders = order_model.objects.all()

    orders_to_delete = []
    orders_to_update = []

    for o in orders:
        if o.status == "Pending":
            o.delivery = o.order_date + timezone.timedelta(days=3)
            orders_to_update.append(o)
        elif o.status == "Completed":
            o.warranty = "24 months"
            orders_to_update.append(o)
        elif o.status == "Cancelled":
            orders_to_delete.append(o)

    if orders_to_delete:
        order_model.objects.filter(pk__in=[o.pk for o in orders_to_delete]).delete()
    if orders_to_update:
        order_model.objects.bulk_update(orders_to_update, ['delivery', 'warranty'])


def reverse_delivery_warranty(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')
    orders = order_model.objects.all()

    default_delivery = None
    default_warranty = order_model._meta.get_field('warranty').default

    for o in orders:
        o.delivery = default_delivery
        o.warranty = default_warranty

    order_model.objects.bulk_update(orders, ['delivery', 'warranty'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(update_delivery_warranty, reverse_code=reverse_delivery_warranty)
    ]
